In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel(r'C:\Users\panda\OneDrive\Desktop\trading_value.xlsm',sheet_name='Sheet2',engine='openpyxl')

In [3]:
print(df)

                             Unnamed: 0          2560        2561        2562  \
0                 มูลค่าซื้อขายสุทธิ 1/           NaN         NaN         NaN
1                ผู้ลงทุนสถาบันในประเทศ  1.036320e+05    184264.0     52007.0
2                 บัญชีบริษัทหลักทรัพย์  1.674700e+04    -15271.0     14873.0
3                ผู้ลงทุนทั่วไปในประเทศ -9.462400e+04    118465.0    -21635.0
4                    ผู้ลงทุนต่างประเทศ -2.575541e+04   -287459.0    -45245.0
5                   มูลค่าซื้อขายรวม 2/  1.798671e+07  22103255.0  21404431.0
6                ผู้ลงทุนสถาบันในประเทศ  2.664909e+06   2958744.0   2943381.0
7                 บัญชีบริษัทหลักทรัพย์  2.553132e+06   3467353.0   3515235.0
8                ผู้ลงทุนทั่วไปในประเทศ  5.412540e+06   5418719.0   4221385.0
9                    ผู้ลงทุนต่างประเทศ  7.356126e+06  10258438.0  10724429.0
10  สัดส่วนมูลค่าซื้อขายรวม (ร้อยละ) 3/  1.000000e+02       100.0       100.0
11               ผู้ลงทุนสถาบันในประเทศ  1.481599e+01        13.4        13.8
12                บัญชีบริษัทหลักทรัพย์  1.419455e+01        16.0        16.0
13               ผู้ลงทุนทั่วไปในประเทศ  3.009189e+01        25.0        20.0
14                   ผู้ลงทุนต่างประเทศ  4.089757e+01        46.4        50.1

          2563          2564          2565
0          NaN           NaN           NaN
1      33456.0 -7.733591e+04 -1.538823e+05
2      14221.0  1.367242e+04 -3.419935e+03
3     216709.0  1.122410e+05 -4.539208e+04
4    -264386.0 -4.857755e+04  2.026944e+05
5   32724715.0  4.262956e+07  3.433084e+07
6    3279550.0  2.975437e+06  2.728872e+06
7    3512425.0  4.232084e+06  2.937970e+06
8   13984214.0  1.870702e+07  1.217734e+07
9   11948525.0  1.671502e+07  1.648665e+07
10       100.0  1.000000e+02  1.000000e+02
11        10.0  6.979750e+00  7.948750e+00
12        11.0  9.927580e+00  8.557815e+00
13        43.0  4.388274e+01  3.547057e+01
14        36.5  3.920993e+01  4.802287e+01

In [4]:
df = pd.DataFrame(df)

In [5]:
df.head(20)

,Unnamed: 0,2560,2561,2562,2563,2564,2565
0,มูลค่าซื้อขายสุทธิ 1/,NaN,NaN,NaN,NaN,NaN,NaN
1,ผู้ลงทุนสถาบันในประเทศ,1.036320e+05,184264.0,52007.0,33456.0,-7.733591e+04,-1.538823e+05
2,บัญชีบริษัทหลักทรัพย์,1.674700e+04,-15271.0,14873.0,14221.0,1.367242e+04,-3.419935e+03
3,ผู้ลงทุนทั่วไปในประเทศ,-9.462400e+04,118465.0,-21635.0,216709.0,1.122410e+05,-4.539208e+04
4,ผู้ลงทุนต่างประเทศ,-2.575541e+04,-287459.0,-45245.0,-264386.0,-4.857755e+04,2.026944e+05
5,มูลค่าซื้อขายรวม 2/,1.798671e+07,22103255.0,21404431.0,32724715.0,4.262956e+07,3.433084e+07
6,ผู้ลงทุนสถาบันในประเทศ,2.664909e+06,2958744.0,2943381.0,3279550.0,2.975437e+06,2.728872e+06
7,บัญชีบริษัทหลักทรัพย์,2.553132e+06,3467353.0,3515235.0,3512425.0,4.232084e+06,2.937970e+06
8,ผู้ลงทุนทั่วไปในประเทศ,5.412540e+06,5418719.0,4221385.0,13984214.0,1.870702e+07,1.217734e+07
9,ผู้ลงทุนต่างประเทศ,7.356126e+06,10258438.0,10724429.0,11948525.0,1.671502e+07,1.648665e+07
10,สัดส่วนมูลค่าซื้อขายรวม (ร้อยละ) 3/,1.000000e+02,100.0,100.0,100.0,1.000000e+02,1.000000e+02
11,ผู้ลงทุนสถาบันในประเทศ,1.481599e+01,13.4,13.8,10.0,6.979750e+00,7.948750e+00
12,บัญชีบริษัทหลักทรัพย์,1.419455e+01,16.0,16.0,11.0,9.927580e+00,8.557815e+00
13,ผู้ลงทุนทั่วไปในประเทศ,3.009189e+01,25.0,20.0,43.0,4.388274e+01,3.547057e+01
14,ผู้ลงทุนต่างประเทศ,4.089757e+01,46.4,50.1,36.5,3.920993e+01,4.802287e+01

pseudo code

In [6]:
df.isnull().sum()

Unnamed: 0    0
2560          1
2561          1
2562          1
2563          1
2564          1
2565          1
dtype: int64

In [10]:
df.dropna(inplace=True)

In [12]:
df.isnull().sum()

Unnamed: 0    0
2560          0
2561          0
2562          0
2563          0
2564          0
2565          0
dtype: int64

In [14]:
df.head()

,Unnamed: 0,2560,2561,2562,2563,2564,2565
1,ผู้ลงทุนสถาบันในประเทศ,103632.00,184264.0,52007.0,33456.0,-7.733591e+04,-1.538823e+05
2,บัญชีบริษัทหลักทรัพย์,16747.00,-15271.0,14873.0,14221.0,1.367242e+04,-3.419935e+03
3,ผู้ลงทุนทั่วไปในประเทศ,-94624.00,118465.0,-21635.0,216709.0,1.122410e+05,-4.539208e+04
4,ผู้ลงทุนต่างประเทศ,-25755.41,-287459.0,-45245.0,-264386.0,-4.857755e+04,2.026944e+05
5,มูลค่าซื้อขายรวม 2/,17986707.00,22103255.0,21404431.0,32724715.0,4.262956e+07,3.433084e+07

In [19]:
df['Unnamed: 0']

1                  ผู้ลงทุนสถาบันในประเทศ
2                   บัญชีบริษัทหลักทรัพย์
3                  ผู้ลงทุนทั่วไปในประเทศ
4                      ผู้ลงทุนต่างประเทศ
5                     มูลค่าซื้อขายรวม 2/
6                  ผู้ลงทุนสถาบันในประเทศ
7                   บัญชีบริษัทหลักทรัพย์
8                  ผู้ลงทุนทั่วไปในประเทศ
9                      ผู้ลงทุนต่างประเทศ
10    สัดส่วนมูลค่าซื้อขายรวม (ร้อยละ) 3/
11                 ผู้ลงทุนสถาบันในประเทศ
12                  บัญชีบริษัทหลักทรัพย์
13                 ผู้ลงทุนทั่วไปในประเทศ
14                     ผู้ลงทุนต่างประเทศ
Name: Unnamed: 0, dtype: object